### ISSUE TITLE
Documentation on the Home page

### ISSUE THREAD

**Issue by Ayushsunny** [INVIII/QuroCare#26]
## Description

All of the texts on this website are automatically generated as Lorem ipsum.

## Describe the solution you'd like

I want 'Lorem Ipsum auto-generated texts to be replaced by suitable texts as per the topic on the Home page

## Additional context

...

**Comment by Dev5902** [comment]
@Ayushsunny  I want to work on the issue.

**Comment by Ayushsunny** [comment]
> @Ayushsunny I want to work on the issue.

Go Ahead
